;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        indent-for-tab-command
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        mc/mark-all-like-this-expand
        mc/mark-next-like-this-expand
        undo-tree-visualize
        ))
