;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        backward-delete-word
        c-electric-delete-forward
        cua-delete-region
        eval-last-sexp
        indent-for-tab-command
        lispy-cursor-down
        lispy-mark-symbol
        paredit-forward-delete
        sgml-slash
        special-lispy-clone
        special-lispy-move-down
        special-lispy-slurp
        special-lispy-tab
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        mc/mark-all-like-this-expand
        mc/mark-next-like-this-expand
        undo-tree-visualize
        ))
