;; Additional global hotkeys
(global-set-key [C-backspace] 'backward-delete-word)
(global-set-key (kbd "M-n") 'scroll-up)
(global-set-key (kbd "M-p") 'scroll-down)
(global-set-key [C-tab] 'other-window)
(global-set-key [?\C-x ?\C-f] 'projectile-find-file-with-fallback)
(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "C-a") 'back-to-indentation-or-beginning)
(global-set-key (kbd "M-/") 'hippie-expand)
(global-set-key (kbd "C-x C-b") 'ibuffer-other-window)
(global-set-key (kbd "C-c C-t") 'ansi-term-default)
(global-set-key (kbd "C-s") 'isearch-forward-regexp)
(global-set-key (kbd "C-r") 'isearch-backward-regexp)
(global-set-key (kbd "C-M-s") 'isearch-forward)
(global-set-key (kbd "C-M-r") 'isearch-backward)
(global-set-key [M-f1] 'projectile-ff-find-other-file)
(global-set-key [f5] 'projectile-compile-with-fallback)
(global-set-key (kbd "C-;") 'ace-jump-word-mode)
(global-set-key (kbd "C-'") 'er/expand-region)
(global-set-key (kbd "C--") 'er/contract-region)
(global-set-key (kbd "M-s M-s") 'sudo-edit)
(global-set-key (kbd "M-.") 'sm-find-tag)
(global-set-key (kbd "C-x 5") 'toggle-frame-split)
(global-set-key (kbd "C-x 4") 'transpose-windows)
(global-set-key (kbd "M-`") 'project-explorer-toggle)
(global-set-key (kbd "M-m") 'helm-mini)
(global-set-key (kbd "M-]") 'move-window-split-right)
(global-set-key (kbd "M-[") 'move-window-split-left)
(global-set-key (kbd "C-x C-x") 'cua-exchange-point-and-mark-center)
(global-set-key (kbd "C-x d") 'duplicate-buffer)

 ;; Key chords
(key-chord-mode t)
(key-chord-define-global "uu" 'undo-tree-visualize)
(key-chord-define-global "JJ" 'switch-to-prev-buffer)
(key-chord-define-global "KK" 'switch-to-next-buffer)
(key-chord-define-global ",," 'mc/mark-all-like-this-dwim)
(key-chord-define-global ";;" 'er/expand-region)

;; Tree undo
(global-unset-key (kbd "C-z"))
(global-set-key (kbd "C-z") 'undo-tree-undo)
(global-set-key (kbd "C-S-z") 'undo-tree-redo)

(provide 'setup-key-bindings)
